// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkLPX3MW79YLutwTvW7txyaqZ7dgveSIU',
    appId: '1:278422724793:web:c307dff0dbccbfb9bbfb68',
    messagingSenderId: '278422724793',
    projectId: 'traveler5454task',
    authDomain: 'traveler5454task.firebaseapp.com',
    storageBucket: 'traveler5454task.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFjeBKUIdzqiq4XJHJosjK5gfsJ-vKao',
    appId: '1:278422724793:android:d9059b5b527141d5bbfb68',
    messagingSenderId: '278422724793',
    projectId: 'traveler5454task',
    storageBucket: 'traveler5454task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaxSecwBelP79jquyN9evakHFv0dUXLw',
    appId: '1:278422724793:ios:f33ecf7018fc9d6ebbfb68',
    messagingSenderId: '278422724793',
    projectId: 'traveler5454task',
    storageBucket: 'traveler5454task.firebasestorage.app',
    iosBundleId: 'com.traveler.travelerTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaxSecwBelP79jquyN9evakHFv0dUXLw',
    appId: '1:278422724793:ios:f33ecf7018fc9d6ebbfb68',
    messagingSenderId: '278422724793',
    projectId: 'traveler5454task',
    storageBucket: 'traveler5454task.firebasestorage.app',
    iosBundleId: 'com.traveler.travelerTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkLPX3MW79YLutwTvW7txyaqZ7dgveSIU',
    appId: '1:278422724793:web:8dc59bd13cb7110abbfb68',
    messagingSenderId: '278422724793',
    projectId: 'traveler5454task',
    authDomain: 'traveler5454task.firebaseapp.com',
    storageBucket: 'traveler5454task.firebasestorage.app',
  );
}
